name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclenche sur chaque push vers "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "Running tests..."
        pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ne se lance qu'après le succès des tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        echo "Setting up Heroku..."
        heroku git:remote -a $HEROKU_APP_NAME
        echo "Deploying to Heroku..."
        git push heroku main


