name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ce workflow se déclenche sur un push vers la branche "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Spécifiez la version de Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ce job dépend du succès du job "test"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Heroku (or another cloud platform)
      run: |
        echo "Configurez le déploiement selon votre plateforme cloud"
